# Generated by Django 6.0.7 on 2026-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='riwayat/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_label', models.CharField(max_length=32)),
                ('kelas', models.CharField(max_length=32)),
                ('label', models.CharField(choices=[('BAIK', 'Baik'), ('PERHATIAN', 'Perhatian'), ('BERMASALAH', 'Bermasalah')], max_length=16)),
                ('color', models.CharField(max_length=16)),
                ('confidence', models.FloatField()),
                ('desc', models.TextField(blank=True)),
                ('rekomendasi', models.TextField(blank=True)),
                ('breakdown', models.JSONField(default=list)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Riwayat Deteksi',
                'verbose_name_plural': 'Riwayat Deteksi',
                'ordering': ['-created_at'],
            },
        ),
    ]
