# Generated by Django 6.0.7 on 2026-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('terang', 'Terang'), ('gelap', 'Gelap')], default='terang', max_length=10)),
                ('satuan_pengukuran', models.CharField(choices=[('mm', 'mm (Milimeter)'), ('inch', 'inch (Inci)')], default='mm', max_length=10)),
                ('zona_waktu', models.CharField(choices=[('Asia/Jakarta', '(UTC+07:00) Jakarta'), ('Asia/Makassar', '(UTC+08:00) Makassar'), ('Asia/Jayapura', '(UTC+09:00) Jayapura')], default='Asia/Jakarta', max_length=32)),
                ('format_tanggal', models.CharField(choices=[('d M Y', 'DD MMM YYYY (12 Mei 2024)'), ('d/m/Y', 'DD/MM/YYYY (12/05/2024)'), ('Y-m-d', 'YYYY-MM-DD (2024-05-12)')], default='d M Y', max_length=16)),
                ('notifikasi_email', models.BooleanField(default=True)),
                ('pengingat_perawatan', models.BooleanField(default=True)),
                ('ringkasan_mingguan', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Aplikasi',
                'verbose_name_plural': 'Pengaturan Aplikasi',
            },
        ),
    ]
