# Generated by Django 6.0.7 on 2026-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi', '0002_pengaturan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturan',
            name='autentikasi_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='bahasa',
            field=models.CharField(choices=[('id', 'Bahasa Indonesia'), ('en', 'English')], default='id', max_length=5),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='push_notification',
            field=models.BooleanField(default=True),
        ),
    ]
