# Generated by Django 6.0.7 on 2026-07-16 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi', '0005_akun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Nonaktifkan untuk menangguhkan akses tanpa menghapus akun.'),
        ),
        migrations.AddField(
            model_name='akun',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Pemilik profil ini. Kosong hanya untuk baris akun peninggalan sebelum multi-user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akun', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayat',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Pengguna yang melakukan deteksi ini (kosong = data lama sebelum multi-user).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='akun',
            name='peran',
            field=models.CharField(choices=[('admin', 'Admin'), ('pengguna', 'Pengguna')], default='pengguna', max_length=16),
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_aktivitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-created_at'],
            },
        ),
    ]
