# Generated by Django 6.0.7 on 2026-07-18 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi', '0007_clear_dummy_notifikasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Pengguna pemilik notifikasi ini (kosong = notifikasi lama sebelum multi-user, ditampilkan ke semua orang untuk kompatibilitas mundur).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifikasi', to=settings.AUTH_USER_MODEL),
        ),
    ]
