# Generated by Django 6.0.7 on 2026-07-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi', '0008_notifikasi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturan',
            name='satuan_pengukuran',
        ),
        migrations.AlterField(
            model_name='pengaturan',
            name='zona_waktu',
            field=models.CharField(choices=[('Asia/Jakarta', '(UTC+07:00) Jakarta')], default='Asia/Jakarta', max_length=32),
        ),
    ]
