# Generated by Django 6.0.7 on 2026-07-19 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi', '0009_remove_pengaturan_satuan_pengukuran_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KredensialFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perangkat', models.CharField(blank=True, help_text="Label bebas biar user bisa bedain kalau daftar dari beberapa perangkat, mis. 'HP Ardi'.", max_length=100)),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField(help_text='Public key COSE, disimpan base64.')),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kredensial_fingerprint', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kredensial Fingerprint',
                'verbose_name_plural': 'Kredensial Fingerprint',
                'ordering': ['-created_at'],
            },
        ),
    ]
