"""
Django settings for tireweb project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-50_&8#naqx!=t=rcw-sfu&d$++o2v8d(76khjd71&3k^m)5)4o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'deteksi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tireweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'deteksi.context_processors.unread_notifications',
                'deteksi.context_processors.akun_aktif',
                'deteksi.context_processors.app_theme',
                'deteksi.context_processors.bahasa_aktif',
                'deteksi.context_processors.format_tanggal_aktif',
            ],
        },
    },
]

WSGI_APPLICATION = 'tireweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'id-id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'deteksi' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (foto ban hasil upload/kamera, disimpan sebagai riwayat nyata)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Upload gambar bisa cukup besar (foto kamera)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

# ============ Autentikasi ============
# Halaman yang dituju kalau user belum login & mengakses view yang
# memakai @login_required (mis. halaman Deteksi / kamera & upload).
LOGIN_URL = 'deteksi:login'
LOGIN_REDIRECT_URL = 'deteksi:deteksi_page'
LOGOUT_REDIRECT_URL = 'deteksi:login'

# Email beneran lewat Gmail SMTP. Wajib pakai App Password (bukan
# password akun Gmail biasa) — akun Google harus sudah aktif
# 2-Step Verification dulu, baru bisa generate App Password di:
# https://myaccount.google.com/apppasswords
#
# Isi via environment variable, JANGAN hardcode credential di sini:
#   export GMAIL_USER="akunkamu@gmail.com"
#   export GMAIL_APP_PASSWORD="16 karakter app password"
#
# Kalau env var belum diisi, otomatis fallback ke console backend
# (email dicetak ke terminal) supaya development tetap jalan tanpa SMTP.
GMAIL_USER = os.environ.get('GMAIL_USER', '')
GMAIL_APP_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD', '')

if GMAIL_USER and GMAIL_APP_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = GMAIL_USER
    EMAIL_HOST_PASSWORD = GMAIL_APP_PASSWORD
    DEFAULT_FROM_EMAIL = f'Deteksi Ban <{GMAIL_USER}>'
else:
    # Fallback development: email dicetak ke terminal, bukan terkirim asli.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Deteksi Ban <noreply@deteksiban.local>'

PASSWORD_RESET_TIMEOUT = 60 * 60  # 1 jam (detik)

# WebAuthn (login fingerprint/biometrik) — RP_ID harus match domain
# tempat app di-akses dari browser (tanpa skema/port), ORIGIN harus
# match persis termasuk skema & port. Default cocok untuk development
# lokal (runserver di localhost:8000); ganti lewat env var saat deploy
# ke domain asli, mis:
#   export WEBAUTHN_RP_ID="tireweb.contoh.com"
#   export WEBAUTHN_ORIGIN="https://tireweb.contoh.com"
WEBAUTHN_RP_ID = os.environ.get('WEBAUTHN_RP_ID', 'localhost')
WEBAUTHN_RP_NAME = 'Deteksi Ban'
WEBAUTHN_ORIGIN = os.environ.get('WEBAUTHN_ORIGIN', 'http://localhost:8000')
